# main.py GPT9

import os
from fastapi import FastAPI, Query
from pydantic import BaseModel, Field
from dotenv import load_dotenv
import openai
from fastapi.responses import StreamingResponse

load_dotenv()

# Create OpenAI client (new SDK syntax)
client = openai.OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

app = FastAPI()

# ===== MCP-STYLE SCHEMAS =====

class QuestionContext(BaseModel):
    """Defines the input context for the LLM interaction"""
    question: str = Field(..., description="The question the user wants answered")

class AnswerOutput(BaseModel):
    """Defines the validated output schema from the LLM"""
    answer: str = Field(..., description="The answer generated by the LLM")

# ===== END SCHEMAS =====

@app.get("/")
def read_root():
    return {"message": "Hello from PydanticAI + OpenAI + MCP-style"}

@app.get("/ask")
def ask(question: str = Query(..., description="User question")):
    # Validate input explicitly (MCP style)
    context = QuestionContext(question=question)

    # Call OpenAI API
    response = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": context.question}
        ],
        temperature=0
    )
    answer_text = response.choices[0].message.content.strip()

    # Validate output explicitly (MCP style)
    validated = AnswerOutput(answer=answer_text)
    return validated

@app.get("/ask-stream")
def ask_stream(question: str = Query(..., description="User question")):
    # Validate input explicitly (MCP style)
    context = QuestionContext(question=question)

    def stream_generator():
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": "You are a helpful assistant."},
                {"role": "user", "content": context.question}
            ],
            temperature=0,
            stream=True
        )
        for chunk in response:
            if chunk.choices[0].delta.content is not None:
                yield chunk.choices[0].delta.content

    return StreamingResponse(stream_generator(), media_type="text/plain")