# main.py GPT10

import os
import json
from fastapi import FastAPI, Query
from pydantic import BaseModel, Field
from dotenv import load_dotenv
import openai

load_dotenv()

client = openai.OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
app = FastAPI()

# === MCP-STYLE SCHEMAS ===

class QuestionContext(BaseModel):
    question: str = Field(..., description="The question the user wants answered")

class AnswerOutput(BaseModel):
    answer: str = Field(..., description="The answer generated by the LLM")

# === TOOL FUNCTION SCHEMA ===

class GetCapitalInput(BaseModel):
    country: str = Field(..., description="Name of the country")

# Tool implementation
def get_capital(country: str):
    capitals = {
        "France": "Paris",
        "Germany": "Berlin",
        "Italy": "Rome",
        "Spain": "Madrid",
        "Japan": "Tokyo"
    }
    capital = capitals.get(country, "Unknown")
    return f"The capital of {country} is {capital}."

# === END SCHEMAS ===

@app.get("/")
def read_root():
    return {"message": "Hello from PydanticAI + OpenAI + MCP + Tool Calling"}

@app.get("/ask-with-tool")
def ask_with_tool(question: str = Query(..., description="User question")):
    # Validate input
    context = QuestionContext(question=question)

    # Define tool for OpenAI (function calling spec)
    tools = [{
        "type": "function",
        "function": {
            "name": "get_capital",
            "description": "Get the capital of a country.",
            "parameters": GetCapitalInput.model_json_schema()  # auto-generate JSON schema!
        }
    }]

    # Call OpenAI with tool option
    response = client.chat.completions.create(
        model="gpt-3.5-turbo-1106",  # function calling works best with 1106 or GPT-4
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": context.question}
        ],
        tools=tools,
        tool_choice="auto",  # Let model decide if/when to call tool
    )

    choice = response.choices[0]

    # Check if tool was invoked
    if choice.finish_reason == "tool_calls":
        tool_call = choice.message.tool_calls[0]
        tool_name = tool_call.function.name
        tool_args = json.loads(tool_call.function.arguments)

        if tool_name == "get_capital":
            # Validate tool input via Pydantic
            validated_args = GetCapitalInput(**tool_args)
            result = get_capital(validated_args.country)
            validated = AnswerOutput(answer=result)
            return validated

    # Otherwise, return normal LLM response
    answer_text = choice.message.content.strip()
    validated = AnswerOutput(answer=answer_text)
    return validated
